# Generated by Django 4.1.1 on 2022-09-16 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_film_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='film.comments'),
        ),
    ]
