# Generated by Django 4.1.1 on 2022-09-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_film_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
